### ISSUE TITLE
Atributo check-project não-reconhecido pela Requisição

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#107]
![image](https://user-images.githubusercontent.com/19597045/32438256-eda81ec4-c2d0-11e7-9088-6f89370017d4.png)
Log disponibilizado pela VPS Dokku de Homolog: http://45.55.176.99

**Comment by alaxalves** [comment]
Ao adicionar um projeto a requisição falha por que esse atributo não é reconhecido

**Comment by cantuariavc** [comment]
O erro persistiu com a mudança do nome da variável?
