### ISSUE TITLE
Redirecionamento do botão sprint errado na show de sprint

### ISSUE THREAD

**Issue by ThalissonMelo** [falko-org/Falko#132]
Quando está dentro de uma sprint específica e clica no botão de sprint na navbar ele redireciona para a página de sprints errada(ele usa o id da sprint como o id da release e por isso há esse bug)

**Comment by brunapinos** [comment]
Tentei reproduzir este bug, mas não apareceu nenhum botão de sprint na navbar. Os únicos botões são de  __Projects__ e __User Profile__. Este comportamento é o correto?

![Captura de tela de 2019-04-23 17-27-55](https://user-images.githubusercontent.com/18364727/56613593-56d58880-65ed-11e9-9694-81a96760396e.png)

**Comment by brunapinos** [comment]
@MatheusRich @matheussbernardo @alaxalves @ThalissonMelo @MartinsLucas

**Comment by MatheusRich** [comment]
@brunapinos Dei uma olhada no código aqui (`Sidebar.vue`) e vi que nem há mais o link pra sprints na sidebar. Provavelmente excluímos esse comportamento. Vou fechar a issue, obrigado pela revisão!
