### ISSUE TITLE
US15 - Pontuar História

### ISSUE THREAD

**Issue by pedrokelvin** [falko-org/Falko#133]
Eu, como usuário, desejo pontuar as histórias com o objetivo de classificar e atribuir peso a elas, bem como facilitar a tomada de decisões dentro do time.

- [X] Não há escala predeterminada para a pontuação.
- [X] A escala deve ser numérica.
- [X] Deve-se escolher se o Projeto pontua histórias ou não.

**Comment by cantuariavc** [comment]
Resolvido no pull request #160
