### ISSUE TITLE
A visualização de GPA na lista de projetos não está visualmente boa

### ISSUE THREAD

**Issue by ThalissonMelo** [falko-org/Falko#136]
* Mudar para uma forma que fique mais bonita

- atualmente está assim
![image](https://user-images.githubusercontent.com/20938232/32675225-5245c5e2-c63d-11e7-9ed1-d543815538ee.png)

**Comment by Matheus456** [comment]
Dá uma olhada no pull request #94 ! Nas imagens ainda está faltando a sombra de cada card, que já foi arrumado.
