### ISSUE TITLE
Elementos aparecendo abaixo da navbar

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#139]
Alguns elementos estão sendo renderizados abaixo na navbar.

![image](https://user-images.githubusercontent.com/20938712/32679931-910a9098-c64f-11e7-9cb2-e1687372424f.png)

**Comment by alaxalves** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/pull/140
