### ISSUE TITLE
User repos quebado

### ISSUE THREAD

**Issue by ThalissonMelo** [falko-org/Falko#174]
Quando se pede pra listar o user repos só se lista os repos do fga-gpp-mds

**Comment by cantuariavc** [comment]
![captura de tela 2017-11-16 as 22 57 49](https://user-images.githubusercontent.com/21143590/32923974-96472b8a-cb21-11e7-97a7-7cdf12ab3780.png)

**Comment by cantuariavc** [comment]
Não entendi o problema.

**Comment by ThalissonMelo** [comment]
Eu resolvi o problema, na verdade era um problema de backend
