### ISSUE TITLE
Us08 Visualizar burndown

### ISSUE THREAD

**Issue by Matheus456** [falko-org/Falko#180]
Eu como usuário desejo visualizar o Burndown de uma sprint com objetivo de acompanhar o desenvolvimento da sprint. 

*Critérios de Aceitação*
- [ ] Criar a visualização do Burndown

**Comment by MatheusRich** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/pull/179
