### ISSUE TITLE
Favicon não aparece em homologação/produção

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#184]
O icone com a logo do Falko não aparece em produção

**Comment by alaxalves** [comment]
![image](https://user-images.githubusercontent.com/19597045/32991896-f77ff53e-cd2a-11e7-9c9f-42404ed4ca79.png)

**Comment by MatheusRich** [comment]
@alaxalves No arquivo "webpack.dev.conf.js" eu tinha adicionado umas linhas para acrescentar o favicon. O script de produção não tem essas linhas, por isso não deve estar aparecendo.

Pode-se observar na linha 30:
![image](https://user-images.githubusercontent.com/20938712/33053208-8e194e44-ce59-11e7-9eb7-b4fa1044f6ef.png)

**Comment by alaxalves** [comment]
![image](https://user-images.githubusercontent.com/19597045/33070904-b7e31d6c-cea0-11e7-85db-1cc069d7c6f5.png)
Ta zuada essa imagem também, acredito que esteja zuada em mais lugares

**Comment by alaxalves** [comment]
Resolvida no PR https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/pull/197
