### ISSUE TITLE
TS 08 - Testes de Aceitação

### ISSUE THREAD

**Issue by MateusO97** [falko-org/Falko#203]
## Comportamento esperado

O sistema deve possuir testes de aceitação automatizados.

## Critérios de Aceitação

- [ ] Componentes da entidade User devidamente testados.
- [ ] Componentes da entidade Project devidamente testados.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by pedrokelvin** [comment]
Resolvido no PR #218
