### ISSUE TITLE
TS 09 - Validações

### ISSUE THREAD

**Issue by MateusO97** [falko-org/Falko#204]
## Comportamento esperado

O sistema deve apresentar um feedback visual para o usuário caso a funcionalidade utilizada seja bem sucedida ou possua algum erro.

## Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.
- [ ] Validações para login e registro de usuário.
- [ ] Feedback para o usuário ao editar ou deletar um componente.
- [ ] Feedback para o usuário ao importar vincular e importar projetos do GitHub.

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
Resolvida no PR #227
