### ISSUE TITLE
TS 04 - Testes Unitários

### ISSUE THREAD

**Issue by MateusO97** [falko-org/Falko#205]
## Comportamento esperado

O sistema deve possuir testes unitários automatizados

## Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.
- [x] Componentes da entidade User devidamente testados.
- [x] Componentes da entidade Project devidamente testados.

## Checklist

- [ ] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [ ] A issue possui nome significativo.

**Comment by cantuariavc** [comment]
Resolvido no Pull Request #236
