### ISSUE TITLE
US 23 - Planejar Sprint

### ISSUE THREAD

**Issue by danieloda** [falko-org/Falko#209]
## Comportamento esperado

O usuário deve ser capaz de classificar as issues de uma determinada sprint.

## **Critérios de Aceitação

- [x] As issues pode ser classificadas.
- [x] Dragabble component
 
## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by alaxalves** [comment]
Resolvida no PR #207
