### ISSUE TITLE
US 20 - Manter EVM

### ISSUE THREAD

**Issue by leossb36** [falko-org/Falko#212]
## Comportamento esperado

O sistema deve apresentar, criar, editar e excluir EVM Agile

## Critérios de Aceitação

- [ ] Front End completo.
- [ ] Back End completo.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MateusO97** [comment]
https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/issues/206
Essa Issue já havia sido criada anteriormente. Favor, fechar essa.
