### ISSUE TITLE
A sessão sempre inicia na homepage

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#216]
## Comportamento esperado
A sessão sempre inicia projetos se o usuário estiver logado.

## Comportamento atual

A sessão sempre inicia na homepage.

## Passos para reproduzir o comportamento
* Acesse `http://localhost:8080/#/`
* Faça login no sistema;
* Feche o navegador;
* Acesse `http://localhost:8080/#/`;
* Você estará na homepage mesmo tendo logado.

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by matheussbernardo** [comment]
Acho que sei como resolver, olhei os ifs no vue router e parece faltar um caso onde a rota é / e o token é diferente de null

**Comment by alaxalves** [comment]
Resolvida no PR #256
