### ISSUE TITLE
Endereço de request na do front na api está errado

### ISSUE THREAD

**Issue by ThalissonMelo** [falko-org/Falko#229]
## Comportamento esperado

o sistema deve mandar o requesto com https

## *Comportamento atual

o sistema manda o requeste com http

## *Passos para reproduzir o comportamento

Usar o sistema em homologação

## Checklist

- [x] A issue possui nome significativo.

*Exclua caso a issue seja uma história

**Comment by cantuariavc** [comment]
Resolvido no Pull Request #228
