### ISSUE TITLE
Fazer Seeds das Sprints passadas

### ISSUE THREAD

**Issue by cantuariavc** [falko-org/Falko#230]
## Comportamento esperado

O Projeto deve ter as Sprints realizadas ao longo do semestre.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui nome significativo.

**Comment by MateusO97** [comment]
Essa é uma issue do BackEnd. Por isso foi criado nele: https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/issues/170
