### ISSUE TITLE
Cant move KanBan issues directly to Doing/Done

### ISSUE THREAD

**Issue by cantuariavc** [falko-org/Falko#235]
## Expected behavior

When transforming the Issue into a Story or Story in Issue, the list must be updated.

## Checklist

- [x] Issue has Labels.
- [ ] Issue has screenshots.
- [x] Issue has significant name.

**Comment by clarissalimab** [comment]
I couldn't reproduce this issue. Can you provide more information about it?

**Comment by alaxalves** [comment]
@clarissalimab When we try to move an issue from "To Do" directly to "Done" the js or something else doesnt allow it.
