### ISSUE TITLE
Typo no .travis.yml

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#246]
## Comportamento esperado

Pipeline desse repo de deploy do .travis.yml deve ser do FrontEnd

## *Comportamento atual

Descreva como o sistema se comporta atualmente.

## *Passos para reproduzir o comportamento

Em caso de bugs, cite quais passos foram executados para chegar no problema.

## Checklist

- [ ] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [ ] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by MatheusRich** [comment]
Resolvida no PR #247
