### ISSUE TITLE
Fazer paginação do backlog (issues)

### ISSUE THREAD

**Issue by Matheus456** [falko-org/Falko#249]
## Comportamento esperado

O backlog deve mostrar todas as issues abertas e que estão alocadas a nenhuma sprint.

## Comportamento atual

O backlog não pega todas as issues quando se trata de um número grande.

## Critérios de Aceitação

- [ ] Páginação das issues.
- [ ] Solicitação no github de todas as issues.

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by danielmarquesr** [comment]
Tentei reproduzir o problema de não aparecer todas as issues no backlog como descrito, mas não a quantidade especificada de issues para a reprodução do erro. Teria como me informar mais sobre os passos para a reprodução do bug ou se já foi corrigido ?

Obs: criei 30 issues para teste e todas elas está aparecendo normalmente.

**Comment by alaxalves** [comment]
@danielmarques28 Na verdade essa issue é referente a uma Feature nova e não um bug. O que pretendemos aqui é tornar a query de issues no GH paginada.

**Comment by MartinsLucas** [comment]
Também não consegui reproduzir o bug descrito na issue. Talvez era algo relacionado à paginação da API do GitHub que foi mudado. Creio que a segunda parte da issue está pronta. A parte da paginação do backlog ainda pode ser feita, paginando a API do Falko, como o @alaxalves explicou, e implementando esta funcionalidade no Front End

**Comment by danielmarquesr** [comment]
Issue solved in this pull requests:
- #367 (front-end);
- falko-org/Falko-API#246 (back-end);
