### ISSUE TITLE
Remover campo de digitar Github

### ISSUE THREAD

**Issue by MateusO97** [falko-org/Falko#251]
## Comportamento esperado

Usuário não deve inserir github no momento de registrar uma nova conta

## Comportamento atual

O usuário deve digitar o github no momento de registrar.

## Passos para reproduzir o comportamento

Abrir homepage e clicar no componente de register.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by alaxalves** [comment]
Resolvida no PR #259
