### ISSUE TITLE
Inserir pontuação e assignee na criação de stories

### ISSUE THREAD

**Issue by ThalissonMelo** [falko-org/Falko#257]
## Comportamento esperado

O sistema deve possibilitar pontuação e assignee na criação da story

## *Comportamento atual

O sistema não possibilita pontuação nem assignee em story atualmente.

## *Passos para reproduzir o comportamento

Crie uma story

## **Critérios de Aceitação

Que seja possível pontuar e dar assignee em uma story.

## Checklist

- [x] A issue possui nome significativo.

**Comment by matheussbernardo** [comment]
Resolved on #295
