### ISSUE TITLE
Layout da página do Backlog quebrado

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#258]
## Comportamento esperado
Título deveria ficar acima da logo.

## Comportamento atual
Título está entre a logo e o botão de add issue.

## Passos para reproduzir o comportamento

* Acesse a página de Backlog, sem nenhuma issue

![image](https://user-images.githubusercontent.com/20938712/33887426-ddac0374-df30-11e7-9c13-2bcb4a840c6b.png)

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by cantuariavc** [comment]
Resolvido no Pull Request #263
