### ISSUE TITLE
Mostrar mensagem de erro caso não seja possível visualizar gráfico de issues

### ISSUE THREAD

**Issue by Matheus456** [falko-org/Falko#267]
## Comportamento esperado

Não visualizar gráfico de issues se existir um erro.

## *Comportamento atual

Sempre exibe o gráfico de issues, mesmo sem issues.

## *Passos para reproduzir o comportamento

Entrar na página de um projeto.

## **Critérios de Aceitação

- [ ] Mostrar erro ao entrar em um projeto sem github
- [ ] Mostrar erro quando o projeto não tiver issues

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by danielmarquesr** [comment]
Issue already solved. #361
