### ISSUE TITLE
Arrumar burndown, alterar as cores e consertar visualização da última sprint

### ISSUE THREAD

**Issue by Matheus456** [falko-org/Falko#270]
## Comportamento esperado

Burndown com cores padronizadas do falko e visualização do gráfico em todas as sprints.

## *Comportamento atual

Cores não seguem o padrão do falko e última sprint não mostra o gráfico.
 
## *Passos para reproduzir o comportamento

Acessar a última sprint de uma release.

## **Critérios de Aceitação

- [x] Cores padrões
- [x] Última sprint mostrar o gráfico

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by MatheusRich** [comment]
Resolvida no PR #271
