### ISSUE TITLE
Alterar tamanho da dashboard (issues)

### ISSUE THREAD

**Issue by Matheus456** [falko-org/Falko#272]
## Comportamento esperado

Dashboard com tamanho correto para nível de zoom 100%

## *Comportamento atual

Dashboard com o tamanho correto para nível de zoom 80%

## *Passos para reproduzir o comportamento

Acessar um projeto que mostre a dashboard

## **Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by MatheusRich** [comment]
Resolvida no PR #273
