### ISSUE TITLE
Não é possível colocar um caractere especial ao final da mensagem de deletar release, dentro da modal

### ISSUE THREAD

**Issue by Matheus456** [falko-org/Falko#274]
## Comportamento esperado

Mensagem: "Delete Relase?"

## *Comportamento atual

Mensagem: "?Delete Release"

## *Passos para reproduzir o comportamento

Acessar releases e clicar em editar

## **Critérios de Aceitação

- [ ] Mensagem: "Delete Release?"

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [ ] A issue possui nome significativo.

**Exclua caso a issue seja um bug

*Exclua caso a issue seja uma história

**Comment by MatheusRich** [comment]
O erro não existe mais.
