### ISSUE TITLE
Dont import without choosing at least one repo

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#276]
## Expected behavior

Shouldnt allow clicking in the 'Import repo' button without choosing at least one repo to import.

## Current behavior

Its possible to click the button without choosing any repo.

## Steps to reproduce

* Click _Import GitHub Repository_.
* Dont select any repo.
* Click _Import_.

![image](https://user-images.githubusercontent.com/20938712/33934978-8b4df194-dfe1-11e7-826b-068cec98eb52.png)

## Checklist

- [x] Issue has Labels.
- [x] Issue has screenshots.
- [x] Issue has significant name.

**Comment by danielmarquesr** [comment]
Issue solved #370.
