### ISSUE TITLE
Arrumar a remoção da última release

### ISSUE THREAD

**Issue by cantuariavc** [falko-org/Falko#284]
## Comportamento esperado

Quando exclui a última release, mostrar as outras releases.

## Comportamento atual

Quando exclui a última release, todas as releases restantes somem.

## Passos para reproduzir o comportamento

Excluir a última release. 

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
Resolvida no PR #293
