### ISSUE TITLE
"Zerar" estados no VueX após logout

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#286]
## Comportamento esperado

Estados devem ser nulos.

## *Comportamento atual

Estados se mentém após o logout.

## *Passos para reproduzir o comportamento

Em caso de bugs, cite quais passos foram executados para chegar no problema.

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by matheussbernardo** [comment]
Resolved no #298 
Please review @ThalissonMelo
