### ISSUE TITLE
Tutorial de Instalação incompleto

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#309]
## Comportamento esperado

O tutorial de instalação não deve apresentar erros.

## Comportamento atual
Ao seguir o tutorial recebi a seguinte mensagem 

> ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
> If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

## Passos para reproduzir o comportamento
* Instale o git;
* Instale o docker;
* Instale o docker compose;
* Clone o repositório;
* Rode `docker-compose up` na raiz do repositório; 

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
@alaxalves poderia me ajudar?

**Comment by alaxalves** [comment]
@MatheusRich Isso acontece porque o usuario não seguiu os [passos pos instalação do docker](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user)

**Comment by alaxalves** [comment]
Acredito que isso não seja uma issue, por isso vou fechar!
