### ISSUE TITLE
Broken layout in Releases

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#317]
## Expected behavior

Número da Release deve estar centralizado no círculo.

## Current behavior

![image](https://user-images.githubusercontent.com/20938712/35945260-ba5311d6-0c46-11e8-981c-48e850c6ede7.png)

## Steps to reproduce

* Create a Release;

OBS.: Apparently when you reload the page (F5), layout goeas back to normal.

## Checklist

- [x] Issue has Labels.
- [x] Issue has screenshots.
- [x] Issue has significant name.

**Comment by danielmarquesr** [comment]
Issue solved #370.
