### ISSUE TITLE
When creating/deleting a release, its Sprints aren't loaded

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#325]
## Expected behavior

* When creating a release, should load its list of sprints.
* When deleting a release, should load its data of previous release - if exists.

## Current behavior
* When creating a release (since there is a previous release) the data of the previous release keep getting displayed.

* When deleting a release, Sprints related to it keep getting displayed.

## Steps to reproduce

(Its needed to have at least one previously created release)
* Create a new release.
---
* Delete a release.

## Checklist

- [x] Issue has Labels.
- [x] Issue has screenshots.
- [x] Issue has significant name.

**Comment by danielmarquesr** [comment]
Issue solved #364
