### ISSUE TITLE
Acceptance tests to every possible flow

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#327]
## Expected behavior

There must be tests regarding the following entities:

- [ ] Release;
- [ ] Sprint;
- [ ] Restrospective;
- [ ] Sprint Review;
- [ ] Issues;
- [ ] Stories;

## Current behavior

There are no tests.

## Checklist

- [x] Issue has Labels.
- [x] Issue has screenshots.
- [x] Issue has significant name.

**Comment by MatheusRich** [comment]
Currently doing the Releses tests.

**Comment by MatheusRich** [comment]
Acredito que essa issue possa ser divida em várias issues. Fica mais fácil até para fazer os Pull Requests.

**Comment by MatheusRich** [comment]
We should make this a Milestone and divide it into several issues.

**Comment by alaxalves** [comment]
@MatheusRich Could you do this??

**Comment by MatheusRich** [comment]
[Done](https://github.com/falko-org/Falko/milestone/1). I'm gonna create those issues now.
