### ISSUE TITLE
Falha de segurança nas dependencias

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#330]
## Comportamento esperado

Sistema sem falhas de segurança de pacotes.

## *Comportamento atual

Problemas de vulnerabilidade nos pacotes.

![image](https://user-images.githubusercontent.com/19597045/37280628-123f14d6-25cd-11e8-97b0-1c54c2aae0f2.png)

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
[Done](https://github.com/falko-org/Falko/pull/337)
