### ISSUE TITLE
Criar `Makefile` pra facilitar execução de comandos

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#331]
## Comportamento esperado

Makefile contendo abstrações de comandos docker.

## *Comportamento atual

Não possui Makefile

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by MatheusRich** [comment]
[Done](https://github.com/falko-org/Falko/pull/339)
