### ISSUE TITLE
Register and Sign Up have no error treatment

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#345]
## Description
If you Register or Sign Up using wrong credentials or whatever there is no way of knowing you've input wrong credentials.

### Expected behavior
Should display error messages.

### Current behavior
No error message

### Steps to reproduce the behavior
Try to Register or Sign Up using wrong/invalid credentials

## Checklist
- [x] This issue has a significant name.
- [x] This issue has labels.
- [ ] This issue has screenshots (if necessary).

**Comment by danielmarquesr** [comment]
Solved in pull request #365.
