### ISSUE TITLE
Weird behavior in Register

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#346]
## Description
When registering a user the inputs of Password or Password Confirmation perform a weird behavior. Even though we put the same password it keep displaying the error message.

### Expected behavior
No error message when fields Password or Password Confirmation are the same.

### Current behavior
Inconsistent error message.

![image](https://user-images.githubusercontent.com/19597045/53686921-739bc100-3d0c-11e9-912b-bd8d2d79e1f6.png)

### Steps to reproduce the behavior
Try to Register a new User.

## Checklist
- [x] This issue has a significant name.
- [x] This issue has labels.
- [x] This issue has screenshots (if necessary).

**Comment by matheussbernardo** [comment]
#359 Closes this issue
