### ISSUE TITLE
Deprecated footer message

### ISSUE THREAD

**Issue by alaxalves** [falko-org/Falko#348]
## Description
Footer has old info

### Expected behavior
Footer must be upgraded

### Current behavior

![image](https://user-images.githubusercontent.com/19597045/53882293-b8697580-3ff4-11e9-909f-fa8867713cb0.png)

### Steps to reproduce the behavior
Scroll down to any page and see the footer.

## Checklist
- [x] This issue has a significant name.
- [x] This issue has labels.
- [x] This issue has screenshots (if necessary).

**Comment by leossb36** [comment]
branch name:
issue_348_deprecated_footer_message

**Comment by danielmarquesr** [comment]
Issue solved #370.
