### ISSUE TITLE
Align components of side and navbar

### ISSUE THREAD

**Issue by leossb36** [falko-org/Falko#357]
## Description
There an icons that's in a wrong position and need to aligned.
![captura de tela de 2019-03-07 17-55-19](https://user-images.githubusercontent.com/26796127/53988458-40897100-4102-11e9-8ea7-1fc789753265.png)

**Comment by danielmarquesr** [comment]
I am not able to reproduce this error of the position of the logout button. Has this bug already been fixed?

**Comment by alaxalves** [comment]
This has been fixed already :D
