### ISSUE TITLE
Date validation avoids creating a new release

### ISSUE THREAD

**Issue by clarissalimab** [falko-org/Falko#358]
## Description
When creating a new release, the date validation says "The Final Date must be after Initial Date.", even when the initial date is smaller than the final date.

### Expected behavior
The application should let the user create a new release if he puts valid dates.

### Current behavior
The application indicates that the dates are not filled correctly and disables the "Save" button. My guess is that when the user starts typing the year on the second date, the form validation indicates that the date is wrong, but it does not update once the user finish typing, just as (#346). 
![image](https://user-images.githubusercontent.com/15739610/55832664-6ed8e280-5aec-11e9-9a8e-29a3559bff15.png)

### Steps to reproduce the behavior
1. Log in
2. Create a new project (not connected to github).
3. Create a new release and 

## Checklist
- [ ] This issue has a significant name.
- [ ] This issue has labels.
- [ ] This issue has screenshots (if necessary).

**Comment by alaxalves** [comment]
@clarissalimab Maybe this should get solved by adding this kind of behavior to VueX logic?! What do you think @matheussbernardo @MatheusRich ??

**Comment by MatheusRich** [comment]
@clarissalimab I'm not sure why this is happening. Maybe the [after validation](https://baianat.github.io/vee-validate/guide/rules.html#after) changed something. I think you could change the validation to the `Initial Date` field and use a [before](https://baianat.github.io/vee-validate/guide/rules.html#before).

**Comment by matheussbernardo** [comment]
@clarissalimab @alaxalves @MatheusRich  I think I know how to fix this and the problem on #346.


When using the `v-validate="'date_format:YYYY-MM-DD|after:Initial Date'"` it is necessary that the that the  **Initial Date Input**  must have ref="Initial Date", that way v-validate can find the target!

This solve the both this issue and #346.

This [stackoverflow question](https://stackoverflow.com/questions/51265450/vue-js-vee-validate-password-confirmation-always-false) explains better.

@clarissalimab Can you make a PR fixing both issues?

**Comment by clarissalimab** [comment]
@matheussbernardo that's correct, it worked! I'll send a PR :)

**Comment by matheussbernardo** [comment]
#359 Closes this issue
