### ISSUE TITLE
Sprints can't be create in release displayed

### ISSUE THREAD

**Issue by brunapinos** [falko-org/Falko#362]
## Description
After creates a release, the user have to be able to create a sprint.

### Expected behavior
Inside the Releases, the user have to be able to create a Sprint for the release displayed.
 
### Current behavior
The sprint is not created unless the user clicks in the release card
![Captura de tela de 2019-05-01 12-37-34](https://user-images.githubusercontent.com/18364727/57025660-353c5880-6c0e-11e9-8f48-b259cccb0a5d.png)

### Steps to reproduce the behavior
* Create a release
* Create a Sprint

## Checklist
- [ ] This issue has a significant name.
- [ ] This issue has labels.
- [ ] This issue has screenshots (if necessary).

**Comment by brunapinos** [comment]
The problem in this issue, is that the releaseId from the release displayed is different from what is in the varible, probably because this variable is not been refreshed.

**Comment by danielmarquesr** [comment]
Issue solved #364
