### ISSUE TITLE
 Error in render: "TypeError: Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by brunapinos** [falko-org/Falko#363]
## Description

When rendering Release page, the following errors happen:

![Captura de tela de 2019-05-01 12-55-09](https://user-images.githubusercontent.com/18364727/57027233-396a7500-6c12-11e9-994b-efcb562221c1.png)

### Steps to reproduce the behavior
* Enter in Releases page.

## Checklist
- [x] This issue has a significant name.
- [x] This issue has labels.
- [x] This issue has screenshots (if necessary).

**Comment by danielmarquesr** [comment]
Issue solved #364
