### ISSUE TITLE
Kanban board does not list any issues.

### ISSUE THREAD

**Issue by wallacybraz** [falko-org/Falko#369]
## Description
Kanban does not list any issues. 

### Expected behavior
When kanban tab is selected, it must show all issues of the current project.

### Current behavior
Kanban board does not list any issues.
![2019-06-02-175708_1848x560_scrot](https://user-images.githubusercontent.com/26303209/58767360-5f13d280-8560-11e9-9672-1c3edf4f571e.png)

### Steps to reproduce the behavior
1. On project selection screen, select a project linked to github with at least one issue one it. 
2. Select some release.
3. Select some sprint.
4. Select Kanban tab.

## Checklist
- [x] This issue has a significant name.
- [ ] This issue has labels.
- [x] This issue has screenshots (if necessary).

**Comment by alaxalves** [comment]
The project you've selected is linked to github? Does that linked project have issues created on GH?

**Comment by wallacybraz** [comment]
> The project you've selected is linked to github? Does that linked project have issues created on GH?

Yes. The request being sent to the api is returning a 404 response. it says that the api does not have any route that matches. Probably due to [this](falko-org/Falko-API#246) change on route settings.
