### ISSUE TITLE
Configure static analysis tool

### ISSUE THREAD

**Issue by brunapinos** [falko-org/Falko#372]
## Description
I noticed that only Falko-API repository have Code Climate configuration, so I tried to also configure to this one but unfortunately, Code Climate does not support Vue projects.

As an alternative, I used [DeepScan](https://deepscan.io) to analyze. This tool doesn't have a badge but is a good tool.

To use it, it's necessary to create a repository team and link a Github account.

Some code improvements will be made using this tool as a guide in [GCES - Falko](https://github.com/gces-falko/Falko), and then open a PR referring to this issue.

## Checklist
- [x] This issue has a significant name.
- [x] This issue has labels.
- [ ] This issue has screenshots (if necessary).

**Comment by gabrielziegler3** [comment]
I could configure the linter tool in the repo, but I'm afraid I would need some permission to do so.

**Comment by gabrielziegler3** [comment]
I have configured the DeepScan tool to analyze the code quality and the results point to a `normal` grade. Several new issues can be created to improve the code quality in Falko's front-end

![image](https://user-images.githubusercontent.com/18370133/66724559-b45ccc00-edfd-11e9-9594-85a892dc186d.png)

Also, DeepScan does provide a badge now! I'll be putting this one in the README.

[![DeepScan grade](https://deepscan.io/api/teams/5721/projects/7548/branches/78603/badge/grade.svg)](https://deepscan.io/dashboard#view=project&tid=5721&pid=7548&bid=78603)

**Comment by MatheusRich** [comment]
Closed by #383
