### ISSUE TITLE
Verificar se Font Awesome está funcionando

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#50]
* Se estiver funcionando, avisar;
* Senão, arrumar. :D

**Comment by MateusO97** [comment]
Já adicionei o comando para o Font Awesome funcionar no nosso projeto, estou usando para fazer a sidebar, quando der o pull request da branch da sidebar já vai estar tudo certo :D

**Comment by cantuariavc** [comment]
#92
