### ISSUE TITLE
Arrumar busca

### ISSUE THREAD

**Issue by MatheusRich** [falko-org/Falko#52]
A busca simplesmente não funciona.

**Comment by cantuariavc** [comment]
Qual o problema?

**Comment by alaxalves** [comment]
Me parece que ela não está buscando kkk @cantuariavc

**Comment by alaxalves** [comment]
O ícone da lupa também não está aparecendo @cantuariavc

**Comment by MateusO97** [comment]
O problema do ícone da lupa era porque ainda não tinhamos a biblioteca do font awesome funcionando. Agora a lupa já está lá e só precisa ajustar sua posição
