### ISSUE TITLE
Feedback - sugestões

### ISSUE THREAD

**Issue by RochaCarla** [falko-org/Falko#61]
A organização das issues esta muito boa (tags, detalhamento). A distribuição de commits ao longo projeto evidencia práticas ágeis. Porém, o tracking do projeto está prejudicado pela falta de organização/padronização das práticas ágeis no projeto. 

- [x] Organização das issues está ruim. Falta uma padronização do uso das labels nas issues. Como vcs estão organizando as sprints? não estão usando a ferramenta para auxilia-los a organizar as issues/sprints. A desorganização dificulta muito a equipe se tornar autogerenciavel/organizavel, além de dificultar a contribuição externa. Dificil acompanhar as entregas das sprints (eh feito soh pela wiki e está desatualizada)

- [x] Nivelamento da equipe - é o grande desafio da disciplina :p foquem nisso! Empoderem o time com atribuições! Vejam:
https://opensource.guide/leadership-and-governance/

- [x] Evitar retrabalho - organizem melhor a wiki de vcs. Façam referência (links) às issues, evitem imagens (baixa rastreabilidade), e definam um padrão de documentação.

- [x] Comunidade de software livre - ainda faltam alguns configurações no repositório para atender os padrões de comunidade de software livre. Deem uma olhada:
https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/community

- [x] Melhorar a comunicação nos pull request

- [x] Transparência - tanto disponibilizar versao homolog quanto disponibilizar versẽos pré-release a cada sprint com o que foi entregue, e pendencias/melhorias (como fizeram na R1).

- [ ] Uma vez organizado o repositório e automatizado o que for possível, foquem no monitoramento, controle, busca de melhor produtividade, evitar desperdício, nivelamento técnico.

**Comment by alaxalves** [comment]
@RochaCarla Esses padrões da comunidade de SW livre devem estar contidos em ambos os repositórios correto??? Tanto o [BackEnd](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd) quanto o [FrontEnd](https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd) ???
